//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rqdesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class requirements
    {
        public int rqId { get; set; }
        public string rqName { get; set; }
        public string rqDescription { get; set; }
        public string rqArea { get; set; }
        public string rqStatus { get; set; }
        public Nullable<System.DateTime> rqFecha { get; set; }
    }
}
